#!/bin/bash

function hasloot() {
    composite -compose darken $1 faces/loot_mask.png bmp:- \
        | compare bmp:- faces/loot_basis.png -metric AE bmp:/dev/null 2>&1 \
        | egrep -q '^0$' && return 0
    composite -compose darken $1 faces/loot_mask.png bmp:- \
        | compare bmp:- faces/loot_basis_2.png -metric AE bmp:/dev/null 2>&1 \
        | egrep -q '^0$' && return 0
    return 1
}

echo -n "Finding and extracting loot popups"
for file in latest/raw/*; do
    if hasloot $file; then
        convert "$file" -crop 223x122+208+129 "latest/images/loot_`basename $file`"
        echo -n "."
    fi
done
echo "done."


