#!/bin/bash

[[ $1 ]] || {
    if lua lp.lua images,mapper=missing | egrep -q '^\[missing\]'; then
        lua lp.lua images,mapper=missing | sort | uniq
        exit 0
    fi

    $0 upload | rsync -avvPh --files-from=- --exclude=.new/ ./ justbob@www.funkyhorror.net:www/toxicfrog/lp/sc/ \
        2>.rsyncerrors
    cat .rsyncerrors | sort | uniq
    rm .rsyncerrors
    exit 0
}

echo common/
find . -type f -iname '*.lua' -or -iname '*.html' -or -iname '*.txt' -or -iname '*.bbcode'
lua lp.lua images,mapper=list

